### ISSUE TITLE
mirador viewer pages in static app don't work when cicognara-static jekyll site is served from digital-cicognara/apps

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/digital-cicognara-library#1]
See, for example, item 10: compared with the repo outside digital-cicognara/apps,  viewpages/10.html and itempages/10.html are identical, yet when served via `bundle exec jekyll serve`, the mirador viewer fails to show up

**Comment by cwulfman** [comment]
Interesting: reloading the page a few times causes it to appear.

**Comment by escowles** [comment]
FWIW, the viewer worked the first time for me when viewing Cico. # 10

**Comment by cwulfman** [comment]
This has been fixed at some point.
