### ISSUE TITLE
Duplicate copies of scripts to generate cicognara-static site

### ISSUE THREAD

**Issue by escowles** [pulibrary/digital-cicognara-library#46]
There are two copies of the scripts to generate the static site:
* `/lib`
* `/apps/cicognara-static/_bin`

We should pick one and remove the other.

Also there are two (AFAICT) unusued directories in `/apps`:
* `/apps/cicosearch`
* `/apps/site`

Can we remove those? `cicosearch` in particular trips me up with tab completion every time.

Items Ming identified with currently-deployed site (built using the `/apps/cicognara-static/_bin` scripts:
- [x] /catalogo/itempages/2962.html does not display Harvard's title
- [ ] /catalogo/itempages/3698.html same
- [ ] /catalogo/itempages/4.html no digital content (was working before)

**Comment by cwulfman** [comment]
<img width="1057" alt="image" src="https://github.com/user-attachments/assets/d2d9b67f-d61a-4f36-bd96-218f7c74cddb">
