### ISSUE TITLE
Catalogo styling

### ISSUE THREAD

**Issue by escowles** [pulibrary/digital-cicognara-library#9]
The styling of the Catalogo (https://cicognara-staging.princeton.edu/catalogo/) is significantly different from the Rails app (https://cicognara.org/catalogo). The style of the Catalogo should be updated to match the old site as closely as possible.

Here are some detailed notes on differences on the main pages:

Home Page
Rails: https://cicognara.org/
Jekyll: http://localhost:4000/
- [x] Search box should be centered and have a white background
- [x] Use a magnifying glass for the search button
- [x] Spacing and size of font for main "The Digital Cicognara Library" title is different
- [x] Black border around the page is missing
- [x] Main content area should be sized to push the partner logo footer off the page
- [x] Center search and title on the page

Catalogo
Rails: https://cicognara.org/catalogo
Jekyll: http://localhost:4000/catalogo/
- [x] Sidebar is too wide and the line spacing is too dense
- [x] Section headers should be sans-serif and larger
- [x] Fonts look slightly different
- [x] Items should have slightly more line spacing, and more spacing between items (including a horizontal rule)
- [x] Item blockquotes should be sans-serif, indented more

Item Page
Rails: https://cicognara.org/catalog/15
Jekyll: http://localhost:4000/catalogo/itempages/15.html
- [x] Fonts and display of Catalogo text should be the same as the Catalogo view
- [x] Display of metadata down the side of the viewer is too cramped and the space is too small for two-column layout. The metadata should display below the viewer, and the viewer should be as wide as the main content area (don't need the tabbed display of contributors because that is now inside the viewer area).

Search Results
Rails: https://cicognara.org/catalog?utf8=%E2%9C%93&search_field=all_fields&q=durer
Jekyll: http://localhost:4000/search.html?q=durer
- [x] Background should be white
- [x] Item fonts, spacing, etc. should be the same as the Catalogo view
- [x] Add more space between items including a horizontal rule

**Comment by escowles** [comment]
Side-by-side screenshots (old Rails site on left, this site on the right):

Home Page:
![1-home](https://github.com/pulibrary/digital-cicognara-library/assets/856924/cdc55c4b-3e95-4817-8493-084313e73f1a)

Catalogo:
![2-catalogo](https://github.com/pulibrary/digital-cicognara-library/assets/856924/5f8eb386-7fe4-412e-b00d-e98d200a2563)

Item Page:
![3-item](https://github.com/pulibrary/digital-cicognara-library/assets/856924/d40c60f1-0958-441e-bc72-7f83a23c9660)

Search Results:
![4-search](https://github.com/pulibrary/digital-cicognara-library/assets/856924/24d77c85-b55b-4f38-8431-4353fb979240)

**Comment by escowles** [comment]
Note: the item and search results pages have significant feature differences (Mirador vs. UV viewer means getting rid of the tab panel, not using Blacklight means not having facets). So "make it look like the old site" only goes so far.

**Comment by kelynch** [comment]
This last issue is more substantial than CSS changes, so I've broken it off into its own ticket - https://github.com/pulibrary/digital-cicognara-library/issues/16
